move non-core functionality out into sub-libraries
Moved logically separable code out into sub-libraries. All chroot code
is now in lib.chroot, all code for generating cache files from the HOST
are in lib.hostcache, and all code for interfacing with sorcery is in
lib.sorcerous.

diff --git a/cauldron/libcauldron b/cauldron/libcauldron
--- a/cauldron/libcauldron
+++ b/cauldron/libcauldron
@@ -15,36 +15,6 @@
 ##
 #-------------------------------------------------------------------------------
 
-#-------------------------------------------------------------------------------
-# cauldron includes
-#-------------------------------------------------------------------------------
-. ${BASE_LIBS}/libinit ||
-  cauldron_fatal_error "error: cannot load base libraries!"
-. ${BASE_LIBS}/liberror ||
-  cauldron_fatal_error "error: cannot load base libraries!"
-. ${BASE_LIBS}/liberrorcodes ||
-  cauldron_fatal_error "error: cannot load base libraries!"
-
-# load cauldron error code and message defines
-. ${CAULDRON_LIBS}/errorcodes ||
-  cauldron_fatal_error "error: cannot load cauldron libraries!"
-
-#-------------------------------------------------------------------------------
-# Sorcery includes
-#-------------------------------------------------------------------------------
-# Needed for modifying config files
-if [[ -e "${SORCERY_LIBS}"/libstate ]]
-then
-  . "${SORCERY_LIBS}"/libstate
-else
-  CAULDRON_HOSTSORCERY=0
-fi
-if [[ -e "${SORCERY_LIBS}"/libtrack ]]
-then
-  . "${SORCERY_LIBS}"/libtrack
-else
-  CAULDRON_HOSTSORCERY=0
-fi
 
 #-------------------------------------------------------------------------------
 ##
@@ -59,56 +29,51 @@ function cauldron_fatal_error() {
 
 #-------------------------------------------------------------------------------
 ##
-## Sources the sorcery config files. Should only be called by
-## cauldron_chroot_init.
+## liberror includes - load these first!
 ##
 #-------------------------------------------------------------------------------
-function cauldron_source_sorcery() {
-  local target=$1
+. ${CAULDRON_BASE}/liberror 2>$CAULDRON_NULL ||
+  cauldron_fatal_error "error: cannot load base libraries!"
 
-  source "$target/etc/sorcery/config" || return $ERR_TARGETSORCERY
-  if [[ -e "$target/etc/sorcery/local/config" ]]
-  then
-    source "$target/etc/sorcery/local/config"
-  fi || return $ERR_TARGETSORCERY
+# load cauldron error code and message defines
+. ${CAULDRON_LIBS}/errorcodes 2>$CAULDRON_NULL ||
+  cauldron_fatal_error "error: cannot load cauldron libraries!"
+
+# drop cauldron_fatal_error if liberror was successfully loaded
+unset cauldron_fatal_error
+
+#-------------------------------------------------------------------------------
+## @param library name to load (no path, just basename)
+##
+## Loads the library given as the first argument. liberror_check_fatal_error is
+## called to check if there was a problem loading the library, and if there was
+## it will print a corresponding error message and then exit with the error
+## $ERR_LOAD_LIBRARY.
+##
+#-------------------------------------------------------------------------------
+function cauldron_load_library() {
+  local lib=$1
+
+  . "$CAULDRON_LIBS/$lib" 2>$CAULDRON_NULL ||
+  liberror_check_fatal_error
 }
 
 #-------------------------------------------------------------------------------
-##
-## Prepares a chroot environment and exports necessary variables
-##
+# cauldron includes
 #-------------------------------------------------------------------------------
-function cauldron_chroot_init() {
-  local TARGET="${1:-$CAULDRON_BUILD}"
+#cauldron_load_library lib.sorcerous
 
-  if [[ "$CAULDRON_CHROOTINIT" -ne 1 ]]
-  then
-    mount --bind "$HOSTPATH"/dev "$TARGET"/dev || ret=$ERR_CHROOTINIT
-    mount --bind "$HOSTPATH"/dev/pts "$TARGET"/dev/pts || ret=$ERR_CHROOTINIT
-    mount --bind "$HOSTPATH"/proc "$TARGET"/proc || ret=$ERR_CHROOTINIT
-    cauldron_source_sorcery "$TARGET" || return $ERR_TARGETSORCERY
-    export CAULDRON_CHROOTINIT=1
-    export CAULDRON_CHROOT="chroot \"$TARGET\""
-  fi
-}
+cauldron_load_library lib.chroot
 
-#-------------------------------------------------------------------------------
-##
-## Cleans up the chroot environment after it is no longer needed
-##
-#-------------------------------------------------------------------------------
-function cauldron_chroot_done() {
-  local TARGET="${1:-$CAULDRON_BUILD}"
+cauldron_load_library lib.init
 
-  if [[ "$CAULDRON_CHROOTINIT" -eq 1 ]]
-  then
-    umount "TARGET"/proc
-    umount "TARGET"/dev/pts
-    umount "TARGET"/dev
-    unset CAULDRON_CHROOTINIT
-    unset CAULDRON_CHROOT
-  fi
-}
+#cauldron_load_library lib.hostcache
+
+if [[ $CAULDRON_COLOR == "yes" ]]
+then
+  . "$CAULDRON_BASE/libcolor"
+  liberror_check_fatal_error
+fi
 
 #-------------------------------------------------------------------------------
 ##
@@ -159,9 +124,6 @@ function cauldron_base_toolchain() {
   local SPELL_CACHE
   local HOST_TRIPLE
 
-  # exit with error if chroot not defined
-  [[ -n "$CAULDRON_CHROOT" ]] || exit $ERR_CHROOT
-
   # set the value for HOST_TRIPLE
   HOST_TRIPLE=$(cauldron_get_host_triple)
 
@@ -188,8 +150,13 @@ function cauldron_base_toolchain() {
         cp "${HOST_SORCERY_SPOOL}/${SPELL_CACHE}" "${CAULDRON_BUILD}"
       else
         # couldn't find a cache file, so we'll need to build one
-        cauldron_build_cache_file ${SPELL}
+        if [[ -z cauldron_build_host_cache_file ]]
+        then
+          cauldron_load_library lib.hostcache
+        fi
+        cauldron_build_host_cache_file ${SPELL}
       fi
+
       # unpack the cache file, effectively installing
       # the spell into the BUILD dir
       # the unpacking is done against the BUILD dir as the root dir, so
@@ -199,87 +166,9 @@ function cauldron_base_toolchain() {
     else
       # the spell is not present on the HOST system, so it must be cast
       # inside a chroot
-      cauldron_chroot_init
-      ${CAULDRON_CHROOT} ${CAULDRON_CAST} ${SPELL}
-      cauldron_chroot_done
+      cauldron_chroot ${CAULDRON_CAST} ${SPELL} || return $ERR_CHROOT
     fi
   done
-}
-
-#-------------------------------------------------------------------------------
-## @param spell
-##
-## Builds a cache file from the information provided by the install log for the
-## spell passed as an argument. It expects the provided spell to include the
-## version as a suffix (i.e. bash-3.2).
-##
-#-------------------------------------------------------------------------------
-function cauldron_create_cache() {
-  local SPELL=$1
-  local INSTALL_LOG="${HOSTPATH}/var/log/sorcery/install/${SPELL}"
-  local CACHE=${CAULDRON_CACHE}/${SPELL}.tar
-
-  create_cache_archive ${INSTALL_LOG} ${CACHE} ${CACHE}${EXTENSION}
-}
-
-#-------------------------------------------------------------------------------
-## @param spell
-## @param aggressive
-##
-## Generates a cache file for the given spell. It will try to use information
-## from an already installed/cast spell (in the case of the host system having
-## sorcery configured to not generate the caches), and, failing that, will cast the
-## spell and then dispel it (the second step only being performed if aggressive
-## is true).
-##
-#-------------------------------------------------------------------------------
-function cauldron_build_cache_file() {
-  local SPELL=$1
-  local AGGRESSIVE=$2
-  local VERSION=
-
-  # First check to see if the spell was installed, but no cache exists.
-  if gaze -q installed $SPELL
-  then
-    # Spell is installed, generate a cache file using the install log?
-    VERSION=$(grep "^${SPELL}" ${HOST_PACKAGES} | cut -d : -f 4)
-    cauldron_create_cache ${SPELL}-${VERSION}
-  else
-    # Only do this part if the caller wants us to be aggressive in building the
-    # cache.
-    if $AGGRESSIVE
-    then
-      # Do some trickery to get a cache file. Make sure that sorcery is set to
-      # generate a cache file, and if not then either set sorcery to do so or
-      # build the cache file afterwards by being recursive? This should be done
-      # in a build chroot so that the user's host filesystem is not polluted.
-      local AGGR_BUILD="$CAULDRON_BUILD/tmp/cauldron_aggressive_cache"
-      if [[ -e "$HOSTPATH/var/log/sorcery/install/${SPELL}-${VERSION}" ]]
-      then
-        rm -fr "$AGGR_BUILD"
-        mkdir -p "$AGGR_BUILD"
-        for file in "$HOSTPATH/var/log/sorcery/install/${SPELL}-${VERSION}"
-        do
-          cp -a --parents "$file" "$AGGR_BUILD"/
-        done
-        tar jcf "${SPELL}-${VERSION}.tar.bz2" \
-          --transform "s#$AGGR_BUILD/##" $AGGR_BUILD/*
-        [[ $? -eq 0 ]] && rm -fr "$AGGR_BUILD"
-      else
-        if [[ -e "$CAULDRON_BUILD/etc/sorcery/local/config" ]]
-        then
-          local CONFIG="$CAULDRON_BUILD/etc/sorcery/local/config"
-          local ARCHIVE=$(grep "ARCHIVE=" "$CONFIG" | cut -d= -f2)
-          [[ $ARCHIVE != "on" ]] &&
-          sed -i 's/ARCHIVE=.*/ARCHIVE="on"/' "$CONFIG"
-        fi
-        cauldron_chroot_init
-        "$CAULDRON_CHROOT" $CAULDRON_CAST $SPELL
-        "$CAULDRON_CHROOT" $CAULDRON_DISPEL $SPELL
-        cauldron_chroot_done
-      fi
-    fi
-  fi
 }
 
 #-------------------------------------------------------------------------------
@@ -296,9 +185,15 @@ function cauldron_build_cache_file() {
 ##
 #-------------------------------------------------------------------------------
 function cauldron_configure_toolchain() {
-  local STAGE=$1
+  local stage=$1
 
-  case ${STAGE} in
+  if [[ -z modify_config ]]
+  then
+    . "${SORCERY_LIBS}"/libtrack 2> $CAULDRON_NULL ||
+      liberror_die $ERR_HOST_SORCERY
+  fi
+
+  case ${stage} in
     1)
       modify_config ${TARGET_LOCAL_CFG} CUSTOM_CFLAGS \
         "--host=${HOST} --target=${TARGET}"
@@ -315,41 +210,29 @@ function cauldron_configure_toolchain() {
 }
 
 #-------------------------------------------------------------------------------
-## @param XXX
 ##
 ## This builds the cross-compiler to produce the TARGET binaries.
 ##
 #-------------------------------------------------------------------------------
 function cauldron_cross_toolchain() {
-  # exit with error if chroot not defined
-  [[ -n "$CAULDRON_CHROOT" ]] || exit $ERR_CHROOT
-
   # build the stage 1 tools
   cauldron_configure_toolchain 1
-  cauldron_chroot_init
-  ${CAULDRON_CHROOT} ${CAULDRON_CAST} binutils
-  ${CAULDRON_CHROOT} ${CAULDRON_CAST} gcc
-  cauldron_chroot_done
+  cauldron_chroot ${CAULDRON_CAST} binutils
+  cauldron_chroot ${CAULDRON_CAST} gcc
 
   # build glibc (stage 2)
   cauldron_configure_toolchain 2
-  cauldron_chroot_init
-  ${CAULDRON_CHROOT} ${CAULDRON_CAST} glibc
-  cauldron_chroot_done
+  cauldron_chroot ${CAULDRON_CAST} glibc
 
   # rebuild gcc (still stage 1, but this time linked against the
   # cross-glibc
   cauldron_configure_toolchain 1
-  cauldron_chroot_init
-  ${CAULDRON_CHROOT} ${CAULDRON_CAST} gcc
-  cauldron_chroot_done
+  cauldron_chroot ${CAULDRON_CAST} gcc
 
   # do a sorcery rebuild inside the BUILD dir to
   # generate the cross-compile tool-chain (stage 3)
   cauldron_configure_toolchain 3
-  cauldron_chroot_init
-  ${CAULDRON_CHROOT} ${CAULDRON_REBUILD}
-  cauldron_chroot_done
+  cauldron_chroot ${CAULDRON_REBUILD}
 }
 
 #-------------------------------------------------------------------------------
@@ -364,15 +247,12 @@ function cauldron_build_target_system() {
   local target_spells=$1
   local spell
 
-  # exit with error if chroot not defined
-  [[ -n "$CAULDRON_CHROOT" ]] || exit $ERR_CHROOT
-
   # Since we will be installing from the running ISO system instead of a giant
   # tarball, for each spell we only need to make sure that the cache file is
   # available. This will require that the ISO sorcery has caching enabled. The
   # caching should really be turned on from the very beginning though...
-  cauldron_chroot_init
   [[ "$ARCHIVE" == "off" ]] && return $ERR_ARCHIVE
+
   for spell in $target_spells
   do
     # Cheap cop-out to get the cache generated - cast the spell to generate the
@@ -380,10 +260,10 @@ function cauldron_build_target_system() {
     # on the ISO filesystem (any spells cast here should be those not required
     # for the functioning of the ISO itself, only to be installed to the target
     # system).
-    ${CAULDRON_CHROOT} ${CAULDRON_CAST} $spell
-    ${CAULDRON_CHROOT} ${CAULDRON_DISPEL} $spell
+    cauldron_chroot ${CAULDRON_CAST} $spell
+    cauldron_chroot ${CAULDRON_DISPEL} $spell
   done
-  cauldron_chroot_done
+
   return $ERR_OK
 }
 
@@ -463,83 +343,24 @@ function cauldron_add_installer() {
 ##
 #-------------------------------------------------------------------------------
 function cauldron_prepare() {
-  # exit with error if chroot not defined
-  [[ -n "$CAULDRON_CHROOT" ]] || exit $ERR_CHROOT
-
-  # first, ensure that the build dir exists
+  # ensure that the build dir exists
   mkdir -p "$CAULDRON_BUILD"
 
   # copy the host's resolv.conf in order to dl packages from net
   cp -L /etc/resolv.conf "$CAULDRON_BUILD"/etc/resolv.conf
 
-  cauldron_sorcery_install "$CAULDRON_BUILD"
-  mkdir -p "$CAULDRON_BUILD"/var/spool/sorcery
-  cp -f "$HOSTPATH"/var/spool/sorcery/sorcery-${SORCERY_BRANCH}.tar${EXTENSION}
+  # install sorcery into the build dir
+  if [[ -z cauldron_sorcery_install ]]
+  then
+    cauldron_load_library lib.sorcerous
+  fi
+  cauldron_sorcery_install "$CAULDRON_BUILD" || return $ERR_SORCERY_INSTALL
 
   # cauldron is a spell
   # there is a spoon
-  cauldron_chroot_init
-  "$CAULDRON_CHROOT" "$CAULDRON_CAST" cauldron
-  cauldron_chroot_done
-}
+  cauldron_chroot "$CAULDRON_CAST" cauldron || return $ERR_CHROOT
 
-#-------------------------------------------------------------------------------
-## @param sorcery_branch
-## @param download_path
-##
-## Downloads a fresh sorcery source tarball from the net, and places it in
-## download_path.
-##
-#-------------------------------------------------------------------------------
-function cauldron_download_sorcery() {
-  local BRANCH=$1
-  local SPOOL=$2
-  local SORCERY="sorcery-$BRANCH.tar.bz2"
-
-  # run in a subshell as an easy way of not messing with the working directory
-  (
-    cd ${SPOOL}
-    wget http://download.sourcemage.org/sorcery/$SORCERY
-  )
-}
-
-#-------------------------------------------------------------------------------
-## @param force_download
-##
-## Installs sorcery into the ISO system. If force_download is "yes", it will
-## download a fresh copy from the net. Otherwise, it will check to see if the
-## sorcery sources are present in the host system, and copy those first, but if
-## they cannot be found it will resort to downloading them. It shouldn't matter
-## if the version of sorcery is a little old, since a system update can be
-## performed inside $CAULDRON_BUILD after the base toolchain is set up. The
-## branch should be one of {stable, test, devel}, and is set in the cauldron
-## config file.
-##
-#-------------------------------------------------------------------------------
-function cauldron_sorcery_install() {
-  local force_download=$1
-  local BRANCH="$ISO_SORCERY_BRANCH"
-  local SPOOL="$CAULDRON_BUILD/var/spool/sorcery"
-
-  # first, check to see if we will copy or download the sorcery source tarball
-  # and get the source tarball and place it in CAULDRON_BUILD
-  if [[ -e "$HOST_SORCERY_SPOOL"/sorcery-${BRANCH}.tar.bz2 ]]
-  then
-    if [[ "$force_download" == "yes" ]]
-    then
-      cauldron_download_sorcery $BRANCH "$SPOOL"
-    else
-      cp "$HOST_SORCERY_SPOOL"/sorcery-${BRANCH}.tar.bz2 "$SPOOL"
-    fi
-  else
-    cauldron_download_sorcery ${BRANCH} "$SPOOL"
-  fi
-
-  # unpack the source tarball
-  tar -C "$CAULDRON_BUILD"/usr/src -jxf "$SPOOL"/sorcery-${BRANCH}.tar.bz2
-
-  # install the source tarball, relative to CAULDRON_BUILD
-  "$CAULDRON_BUILD"/usr/src/sorcery/install "$CAULDRON_BUILD"
+  return $ERR_OK
 }
 
 #-------------------------------------------------------------------------------
@@ -548,8 +369,16 @@ function cauldron_sorcery_install() {
 ##
 #-------------------------------------------------------------------------------
 function cauldron_cleanup() {
-  [[ ${CAULDRON_CLEAN} == "yes" ]] && rm -fr "$CAULDRON_BUILD"
-  rm -fr "$CAULDRON_TMP"
+  # if the user wants everything cleaned, kill the build directory
+  if [[ ${CAULDRON_CLEAN} == "yes" ]]
+  then
+    rm -fr "$CAULDRON_BUILD" || return $ERR_CLEANUP
+  fi
+
+  # kill the temp directory
+  rm -fr "$CAULDRON_TMP" || return $ERR_CLEANUP
+
+  return $ERR_OK
 }
 
 #-------------------------------------------------------------------------------
