liberror: use preserved return value
Preserve the return value to check before doing anything else in the
function. All tests, commands, etc. run will modify the value of $?, so
it needs to be preserved or what is tested later will actually be the
return value of function-internal processing, rather than the value the
caller wants to check.

diff --git a/liberror b/liberror
--- a/liberror
+++ b/liberror
@@ -92,10 +92,12 @@ LIBERROR_CONTEXT=${LIBERROR_CONTEXT:-C}
 ##
 #-------------------------------------------------------------------------------
 function cauldron_checkerror() {
+  # store the return value to preserve it
+  local rc="$?"
   local type=$1
   local error=
 
-  if [[ $? -gt 0 ]]
+  if [[ $rc -gt 0 ]]
   then
     error=$type
   else
