delint: check error codes for internel consistency
Added some new checks against the error codes. Error codes are now
cross-checked against the error messages to make sure that for every
code defined there is a corresponding message, and vice versa.

diff --git a/delint/libdelint b/delint/libdelint
--- a/delint/libdelint
+++ b/delint/libdelint
@@ -71,6 +71,66 @@ function delint_global_variables() {
   done
 }
 
+function delint_error_codes() {
+  local errorcodes="$1"
+  local codes=()
+  local msgcode=""
+  local count=""
+
+  # make sure the defines file exists, otherwise we can't check anything
+  if [[ ! -f "$errorcodes" ]]
+  then
+    libcolor_error "error: error code file \"$errorcodes\" not found"
+    echo ""
+    liberror_die $ERR_FATAL
+  fi
+
+  if ! source "$errorcodes" 2 > /dev/null
+  then
+    libcolor_error "error: could not source error code file \"$errorcodes\""
+    echo ""
+  fi
+
+  # get the list of defined error codes
+  codes=( $(grep -o '^ERR_[A-Z_]\+[0-9]*' "$errorcodes" | grep -v 'ERR_MSGS') )
+
+  # test if the number of messages matches the number of error codes
+  if [[ "${#codes[@]}" -ne "${#ERR_MSGS[@]}" ]]
+  then
+    libcolor_error "error: number of error codes not equal to "
+    libcolor_error "number of messages in \"$errorcodes\""
+    echo ""
+    libcolor_error "     codes: ${#codes[@]}"
+    echo ""
+    libcolor_error "  messages: ${#ERR_MSGS[@]}"
+    echo ""
+
+    echo "${codes[@]}"
+  fi
+
+  # for every error code defined, make sure there is a corresponding message
+  for ((count=0; "$count" < "${#codes[@]}"; count++))
+  do
+    if ! grep -q "${codes[count]}\$" "$errorcodes"
+    then
+      libcolor_error "error: ${codes[count]} defined but has no corresponding message"
+      echo ""
+    fi
+  done
+
+  # for every error message defined, make sure there is a corresponding code
+  for ((count=0; "$count" < "${#ERR_MSGS[@]}"; count++))
+  do
+    msgcode=$(grep "${ERR_MSGS[count]}.*# " "$errorcodes" | sed 's/.*# //')
+
+    if ! grep -q "^${msgcode}=" "$errorcodes"
+    then
+      libcolor_error "error: $msgcode not defined but message is"
+      echo ""
+    fi
+  done
+}
+
 #-------------------------------------------------------------------------------
 ##
 ## This software is free software; you can redistribute it and/or modify
