Branch test to stable, integrate test to devel

diff --git a/iso/skeleton/usr/share/smgl.install/modules/10common b/iso/skeleton/usr/share/smgl.install/modules/10common
--- a/iso/skeleton/usr/share/smgl.install/modules/10common
+++ b/iso/skeleton/usr/share/smgl.install/modules/10common
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+LOCK_DIR=/tmp/lock-dir
+
 # 10 so it gets sources first, fwiw
 #this file contains all the functions that might be needed by other
 # modules
@@ -7,20 +9,15 @@
 
 # wrapper for dialog, should eventually replace the ugly ${DIALOG[*]}
 function run_dialog() {
-  debug_log "common" "run_dialog called with the following arguments:"
-  local arg
-  for arg in "$@" ;do
-    debug_log "dialog_param" "$arg"
-  done
-  "${DIALOG[@]}" "$@"
-  # TODO: Was too lazy to really make this do something, eventually
-  #       should define all the dialog stuff here
-}
+  debug_sleep "pre-dialog"
+  debug_log "dialog" 3 "run_dialog called with the following arguments:" "$@"
 
-# press_enter: display a single line and wait for the user to press enter
-# SECTION: MISC
-function press_enter() {
-  read -p "Press enter..."
+  dialog --backtitle "Source Mage GNU/Linux Installer v. ${INSTALLER_VERSION}" \
+         --stdout --cr-wrap "$@"
+
+  local rc=$?
+  [[ $rc == 255 ]] && debug_log "ERROR" -1 "run_dialog failed, params:" "$@"
+  return $rc
 }
 
 # explode(): split up a string into an array at a given delimiter
@@ -66,7 +63,7 @@ function explode()
 function inputbox()  {
 
   run_dialog  --nocancel --inputbox "$1" \
-    $(( $( echo "$1" | wc -l) + 6)) 60 "$2"
+    0 0 "$2"
 
 }
 
@@ -74,21 +71,9 @@ function inputbox()  {
 # usage: chroot_cmd cmd args...
 function chroot_cmd() {
 
-#  mount --bind /dev  "${TARGET}/dev"
-#  mount --bind /proc "${TARGET}/proc"
-#  mount --bind /var/cache/sorcery "${TARGET}/var/cache/sorcery"
-
-  debug_log "common" "chroot_cmd called with the following arguments:"
-  local arg
-  for arg in "$@" ;do
-    debug_log "chroot_param" "$arg"
-  done
+  debug_log "chroot_cmd" 3 "chroot_cmd called with the following arguments:" "$@"
 
   chroot "${TARGET}" "$@"
-
-#  umount "${TARGET}/dev"
-#  umount "${TARGET}/proc"
-#  umount "${TARGET}/var/cache/sorcery"
 
 }
 
@@ -98,33 +83,42 @@ function chroot_cmd() {
 # SECTION: MISC
 function confirm()  {
 
-#  if  [ "$CONFIRM"  != "on" ]; then
-#    [  -z  "$2"  ]
-    # return false if there probably was a --defaultno in $2
-#  else
     local query="$1"
-    local length=$(( $( echo "$1" | wc -l) + 4))
     shift
-    run_dialog "$@" --yesno  "$query" $length 60
-#  fi
+    run_dialog "$@" --yesno  "$query" 0 0
 
+}
+
+# Displays a dialog menu for the given entries, and remembers the last answer.
+# When the same menu is ran again, it re-uses the answer as default.
+# Args:
+# $1: internal identifier (for remembering)
+# $2: menu title
+# $3: additional options (e.g. --item-help) - no quoting possible
+# $4: menu text
+# $5: initial default selection
+# $*: menu items
+function memory_menu() {
+  local ID="$1"
+  local TITLE="$2"
+  local OPTS="$3"
+  local TEXT="$4"
+  local DEF="$5"
+  shift 5
+  local USEDEF="$(get_dependency "remember_$ID" 2>/dev/null)"
+  USEDEF="${USEDEF:-"$DEF"}"
+  local ANSWER
+  ANSWER=$(run_dialog --title "$TITLE"      \
+                 --default-item "$USEDEF"   \
+                 --menu "$TEXT" 0 0 0       \
+                 "$@")                      &&
+  fill_dependency "remember_$ID" "$ANSWER"  &&
+  echo "$ANSWER"
 }
 
 # displays a message
 function display_message() {
-  run_dialog --msgbox "$1" 10 60
-}
-
-function debug_log() {
-  local func=$1
-  shift
-  echo "$(date +%H:%M:%S) ${func}($$): $*" >>${INSTALLER_DEBUG}
-}
-
-# deprecated
-function debug_screen() {
-#$1 is the message to show
-  display_message "DEBUG: $1"
+  run_dialog --msgbox "$1" 0 0
 }
 
 #adding some functions for dependency management
@@ -164,28 +158,44 @@ function check_dependency() {
 # at user's own risk
 # otherwise fall out to the main menu?
 # $1 is depends key
-function interactive_do_depends() {
-  if check_dependency $1; then
-#    debug_screen "successful depends find"
-    echo "successfully found fulfilled $1"
-    return 0
-  else
-    if confirm "Depends $1 not fulfilled. Force fulfill (only way to continue)?"
-    then
-      #ok was selected
-      fill_dependency $1 force
-      return 0
-    else
-      return 1
-    fi
-  fi
+function need_dependency() {
+  check_dependency $1 ||
+  {
+    confirm "The selected step needs $1 to be done first.
+Do you want to continue anyway and skip $1?" --defaultno &&
+    fill_dependency $1 force
+  }
+}
+
+# Ask the user if he wants to do this yet,
+# it's physically possible but rarely done in that order
+function want_dependency() {
+  check_dependency $1 ||
+  confirm "Normally, $1 is done before this step. Continue anyway?"
 }
 
 # Blocks until specified stuff is fulfilled
 function wait_depends() {
-  while ! check_dependency $* ;do
+  while ! check_dependency "$@" ;do
     sleep 10
   done
+}
+
+# Lock specified resource
+# waits until specified resource is not locked, then locks it
+# $1: resource to lock
+function lock_resource() {
+  mkdir -p $LOCK_DIR
+  while [ -e $LOCK_DIR/$1 ] ;do
+    sleep 1
+  done
+  echo $$ >$LOCK_DIR/$1
+}
+
+# Unlock specified resource
+# $1: resource to unlock
+function unlock_resource() {
+  rm -f $LOCK_DIR/$1
 }
 
 #dkowis discovered dialog's progress bar!
@@ -209,4 +219,3 @@ function progress_bar() {
         echo $PCT
     done | run_dialog --title "${2}" --gauge "${3}" 10 70 0
 }
-
diff --git a/iso/skeleton/usr/share/smgl.install/modules/30spellinstall b/iso/skeleton/usr/share/smgl.install/modules/30spellinstall
--- a/iso/skeleton/usr/share/smgl.install/modules/30spellinstall
+++ b/iso/skeleton/usr/share/smgl.install/modules/30spellinstall
@@ -1,69 +1,93 @@
 #!/bin/bash
-# Contains the spell installation functions, as specified on the wiki.
-# Non-backgrounding version
+# Contains the spell installation functions, as specified on sourcemage.org
+# backgrounding version
 
 # NEEDS: a /var/state/sorcery/depends containing all depends between
 #        spells that could be installed
 #        a /var/state/sorcery/packages containing all spells that could
 #        get installed and their versions
-#        /var/state/smgl.install/depends containing lines of the form
+#        /var/state/smgl.install/conflicts containing lines of the form
 #        spell;conflicts_with
 
 # --------------public----------------------
 
 SI_QUEUE_DIR=/tmp/spellinstall
-SI_UNLOOP_FILE=$SI_QUEUE_DIR/antiloop
-SI_UNLOOP_FILE2=$SI_QUEUE_DIR/antiloop2
 SI_SPELL_QUEUE=$SI_QUEUE_DIR/queue
 SI_CONFLICTS=$SI_QUEUE_DIR/conflicts
+SI_INSTALLING=$SI_QUEUE_DIR/installing
 
 
 # Marks a spell for installation. Does not install it.
 # args: the spells
-# $1 (if a number) recursion depth - to recognize loops
 si_queue() {
   mkdir -p ${SI_QUEUE_DIR}
-  touch $SI_UNLOOP_FILE
-  local spell
-  for spell in "$@" ;do
-    if ! grep -q "^$spell$" $SI_UNLOOP_FILE ;then
-      echo "$spell" >>$SI_UNLOOP_FILE
-      # No spell gets handled twice, => no infinite loops on circular deps
-      si_queue $( si_get_dependencies $spell )
-      si_run_conflicts $spell
-      echo "$spell" >>${SI_SPELL_QUEUE}
-    fi
-  done
+  >$SI_QUEUE_DIR/tmpqueue
+  >$SI_QUEUE_DIR/tmpqueue.unloop
+
+  recursively_make_queue $SI_QUEUE_DIR/tmpqueue "$@"
+
+  si_run_conflicts $(cat $SI_QUEUE_DIR/tmpqueue)
+
+  lock_resource SI_SPELL_QUEUE
+  # Resource is called SI_SPELL_QUEUE, not $SI_SPELL_QUEUE
+  cat $SI_QUEUE_DIR/tmpqueue >>${SI_SPELL_QUEUE}
+  unlock_resource SI_SPELL_QUEUE
+
+  rm -f $SI_QUEUE_DIR/tmpqueue $SI_QUEUE_DIR/tmpqueue.unloop
 }
 
-# (currently) installs a spell
+# inserts a spell and its dependencies at the top of the spell queue
 # args: the spells to install
-# TODO: Could get a nice progress bar too
 si_queue_now() {
-  touch $SI_UNLOOP_FILE2
-  local spell
-  for spell in "$@" ;do
-    if ! grep -q "^$spell$" $SI_UNLOOP_FILE2 ;then
-      echo "$spell" >>$SI_UNLOOP_FILE2
-      si_queue_now $( si_get_dependencies $spell )
-      si_run_conflicts $spell
-      si_install_spell $spell
-    fi
-  done
+  mkdir -p ${SI_QUEUE_DIR}
+  >$SI_QUEUE_DIR/tmpqueue
+  >$SI_QUEUE_DIR/tmpqueue.unloop
+
+  recursively_make_queue $SI_QUEUE_DIR/tmpqueue "$@"
+
+  si_run_conflicts $(cat $SI_QUEUE_DIR/tmpqueue)
+
+  lock_resource SI_SPELL_QUEUE
+  cat $SI_SPELL_QUEUE >>$SI_QUEUE_DIR/tmpqueue # The other way around here
+  mv $SI_QUEUE_DIR/tmpqueue $SI_SPELL_QUEUE
+  unlock_resource SI_SPELL_QUEUE
+
+  rm -f $SI_QUEUE_DIR/tmpqueue.unloop
 }
 
-# ditto
+# marks a spell for installation and does not return until it is installed
 # args: the spells to install
 si_wait() {
   si_queue_now "$@"
+  local spell
+  for spell in "$@" ;do
+    si_query $spell
+    while [[ $? != 3 ]] ;do
+      echo -en '\r\033[2K'
+      echo -n "waiting for $spell... (now installing $(cat $SI_INSTALLING))"
+      test -e $SI_QUEUE_DIR/debug && touch $SI_QUEUE_DIR/force_run
+      sleep 1
+      si_query $spell
+    done
+    echo -en '\r\033[2K'
+    echo "done  with  $spell."
+  done
+  true
 }
 
-# Returns 1 if the spell is queued, 4 if it is installed,
-# 10 if it would conflict with a queued/installed spell, 0 (true) otherwise
+# Returns 1 if the spell is queued, 2 if it is getting installed,
+# 3 if it is installed, 10 if it would conflict with a queued/installed spell
+# 0 (true) otherwise
 # $1: the spell
 si_query() {
-  if grep -q "^$1:" ${TARGET}/var/state/sorcery/packages ;then
-    return 4
+  touch $SI_INSTALLING $SI_SPELL_QUEUE $SI_CONFLICTS
+
+  if si_get_fake_spell "$1" ;then
+    return 3
+  elif grep -q "^$1:" ${TARGET}/var/state/sorcery/packages ;then
+    return 3
+  elif grep -q "^$1$" $SI_INSTALLING ;then
+    return 2
   elif grep -q "^$1$" $SI_SPELL_QUEUE ;then
     return 1
   elif grep -q "^$1$" $SI_CONFLICTS ;then
@@ -76,20 +100,51 @@ si_query() {
 # Casts all spells remaining in the queue
 # no arguments
 si_flush() {
-  if ! [ -e $SI_SPELL_QUEUE ] ;then
-    return 0 #no queue, empty queue
-  fi
+  echo "Waiting for all spells left to complete..."
+  while [ -s $SI_SPELL_QUEUE ] ;do
+    test -e $SI_QUEUE_DIR/debug && touch $SI_QUEUE_DIR/force_run
+    echo -en '\r\033[2K'
+    echo -n "installing $(cat $SI_INSTALLING)..."
+    sleep 1
+  done
+}
 
-  # This will stop working the moment we're multitasking, but it works for now
-  local spell
-  while read spell ;do
-    si_install_spell $spell <&2
-    # Get stdin back, if something goes wrong don't read out the queue file
-  done <$SI_SPELL_QUEUE
-  >${SI_SPELL_QUEUE} #empty queue, we've done these
+# Casts top of queue and removes it
+# no arguments
+si_pop() {
+  if test -s $SI_SPELL_QUEUE ;then
+    spell=$(head -n 1 $SI_SPELL_QUEUE)
+    si_install_spell "$spell" ||
+    debug_log "ERROR" -1 "Failed to install $spell"
+    lock_resource SI_SPELL_QUEUE
+    sed -i "/^$spell$/d" $SI_SPELL_QUEUE
+    unlock_resource SI_SPELL_QUEUE
+    return 0
+  else
+    return 1
+  fi
 }
 
 # --------------private-------------------
+
+# Cycles down the dependency tree, puts the spell and its dependencies
+# sorted dependency-first into a file
+# args: $1: filename to put the queue in
+# Internally uses $1.unloop as file to check for loops - make sure
+# it exists and is empty before calling
+recursively_make_queue() {
+  local spell
+  local queue=$1
+  shift
+  for spell in "$@" ;do
+    if ! grep -q "^$spell$" $queue.unloop ;then
+      echo "$spell" >>$queue.unloop
+      # No spell gets handled twice, => no infinite loops on circular deps
+      recursively_make_queue $queue $( si_get_dependencies $spell )
+      echo "$spell" >>$queue
+    fi
+  done
+}
 
 # Our own conflicts handling.
 # Quite cheap, but ought to do its job.
@@ -97,8 +152,11 @@ si_flush() {
 # Appends any conflicts found to the end of $SI_CONFLICTS.
 
 function si_run_conflicts() {
-  grep "^$1;" $STATE_DIR/conflicts |
-    cut -d';' -f2 >>$SI_CONFLICTS
+  local spell
+  for spell in "$@" ;do
+    grep "^$spell:" $STATE_DIR/conflicts |
+      cut -d':' -f2 >>$SI_CONFLICTS
+  done
 }
 
 # Cheapo checking dependencies.
@@ -111,41 +169,65 @@ si_get_dependencies() {
 }
 
 # If we want any (backgrounded) action filed like a spell.
-# Fake spells should be calles "special:<name>", the colon
-# making sure no real spell can have the same name.
+# Fake spells should be calles "Iso.<name>",
+# we hope no real spell has the same name.
 
-# WARNING: Should always return true if it is a fake spell.
-# Returning false is reserved for real spells.
-si_run_fake_spell() {
+# Returns true when $1 is a fake spell
+si_is_fake_spell() {
+  [[ "$1" == Iso.* ]]
+}
+
+# Return true when the given fake spell is "installed"
+si_get_fake_spell() {
   case $1 in
-    "special:caches")
-                     local TOTALFILES=`ls -1 /var/cache/sorcery | wc -l`
-                     local file
-                     for file in /var/cache/sorcery/* ; do
-                       # Sacrifice some performance for prettiness ;-)
-                       cp --parents $file ${TARGET}
-                       echo $file
-                     done |
-                       progress_bar $TOTALFILES "Installing Source Caches..." \
-                        "Installing Source Cache" "Installing"
-                     fill_dependency install_caches
-                     return 0
-                   ;;
-    "special:basics")
-                     fill_dependency basic_system
-                     return 0
-                   ;;
-    "special:compile_env")
-                          check_dependency compile_system ||
-                          chroot_cmd scribe reindex
-                          fill_dependency compile_system
-                          return 0
-                        ;;
-    special:*)
-              return 0
-            ;;
+    "Iso.Caches")
+                 check_dependency install_caches
+               ;;
+    "Iso.Basics")
+                 check_dependency basic_system
+               ;;
+    "Iso.Compile_env")
+                      check_dependency compile_system
+                    ;;
+    Iso.*)
+          return 0
+        ;;
+    *)
+      return 1
+    ;;
   esac
-  return 1
+}
+
+si_run_fake_spell() {
+  debug_log "spellinstall" 2 "installing fake spell $1"
+  case $1 in
+    "Iso.Caches")
+                 local TOTALFILES=`ls -1 /var/cache/sorcery | wc -l`
+                 local file
+                 for file in /var/cache/sorcery/* ; do
+                   # Sacrifice some performance for prettiness ;-)
+                   cp --parents $file ${TARGET}
+                   echo $file
+                 done |
+                   progress_bar $TOTALFILES "Installing Source Caches..." \
+                    "Installing Source Cache" "Installing"
+                 fill_dependency install_caches
+               ;;
+    "Iso.Basics")
+                 fill_dependency basic_system
+               ;;
+    "Iso.Compile_env")
+                      check_dependency compile_system ||
+                      chroot_cmd scribe reindex
+                      fill_dependency compile_system
+                    ;;
+    Iso.*)
+          return 0
+        ;;
+    *)
+      return 1
+    ;;
+  esac
 }
 
 # Theses functions solely exists to quickfix spells that don't work properly
@@ -169,12 +251,17 @@ si_post_workaround() {
             ;;
     "openssh")
               rm -f ${TARGET}/etc/ssh/*host*
-              chroot_cmd ssh-keygen -t rsa1 -f /etc/ssh/ssh_host_key -N ""
-              chroot_cmd ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ""
-              chroot_cmd ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N ""
+              chroot_cmd ssh-keygen -t rsa1 -f /etc/ssh/ssh_host_key     -N ""
+              chroot_cmd ssh-keygen -t rsa  -f /etc/ssh/ssh_host_rsa_key -N ""
+              chroot_cmd ssh-keygen -t dsa  -f /etc/ssh/ssh_host_dsa_key -N ""
             ;;
       "gnupg")
               mkdir -p -m 700 $TARGET/root/.gnupg
+            ;;
+"netkit-base")
+              sed -i \
+              "s/^127.0.0.1.*/127.0.0.1	localhost	$(cat /etc/hostname)/" \
+              $TARGET/etc/hosts
             ;;
   esac
 }
@@ -182,37 +269,50 @@ si_post_workaround() {
 # $1: the spell to install
 si_install_spell() {
 
-  debug_log "spellinstall" "considering to install $1"
+  debug_log "spellinstall" 2 "considering to install $1"
 
-  if si_run_fake_spell $1 ;then
-    return 0 #is a fake spell, nothing left to do
+  if si_is_fake_spell $1 ;then
+    echo "$1" >$SI_INSTALLING
+    si_run_fake_spell $1
+    local rc=$?
+    >$SI_INSTALLING # Clear file
+    return $rc #nothing left to do
   fi
 
   if grep -q "^$1:" ${TARGET}/var/state/sorcery/packages ;then
+    debug_log "spellinstall" 3 "discarding $1 as already installed"
     return 0 #already installed
   fi
 
   echo "Installing $1..." >&2
+  debug_log "spellinstall" 2 "starting install of $1"
+  echo "$1" >$SI_INSTALLING
 
   # TODO: The backgrounded version should be locking now,
   #       and logging the current spell
-  si_pre_workaround $1        &&
+  debug_log "spellinstall" 3 "running pre_workaround for $1"
+  si_pre_workaround $1                                     &&
 
-  local VERSION               &&
-  VERSION=$(grep "^$1:" /var/state/sorcery/packages | cut -d: -f4) &&
+  local VERSION=$(grep "^$1:" /var/state/sorcery/packages | cut -d: -f4) &&
   if [ -z $VERSION ] ;then
     echo "The spell $1 does not seem to be on this CD!?" >&2
+    debug_log "ERROR" -1 "Not finding spell $1"
     return 1
-  fi                          &&
+  fi                                                       &&
   # TODO: I don't like using *'s
+  debug_log "spellinstall" 3 "installing files for $1"     &&
   tar -xjp -C ${TARGET} -f /var/cache/sorcery/$1-${VERSION}-*.tar.bz2 &&
-    if [[ "$1" != "smgl-fhs" ]] ;then
-      chroot_cmd /sbin/ldconfig
-    fi                        &&
-
-  si_post_workaround $1       &&
+  if [[ "$1" != "smgl-fhs" ]] ;then
+    debug_log "spellinstall" 3 "ldconfig for $1"           &&
+    chroot_cmd /sbin/ldconfig
+  fi                                                       &&
 
   echo "$1:$(date +%Y%m%d):installed:${VERSION}" \
-    >>${TARGET}/var/state/sorcery/packages &&
-  debug_log "spellinstall" "successfully installed $1"
+    >>${TARGET}/var/state/sorcery/packages                 &&
+
+  debug_log "spellinstall" 3 "post_workaround for $1"      &&
+  si_post_workaround $1                                    &&
+
+  debug_log "spellinstall" 1 "successfully installed $1"   &&
+  >$SI_INSTALLING # Clear file
 }
