ward: update function/variable names
Now that delint is renamed to ward, update the function and variable
prefixes accordingly.

diff --git a/ward/functions b/ward/functions
--- a/ward/functions
+++ b/ward/functions
@@ -3,8 +3,8 @@
 ##
 ##=head1 SYNOPSIS
 ##
-##  Function delinter - tests all functions (as defined in the API
-##  specification) for whether they are defined in a given file.
+##  Function ward - tests all functions (as defined in the API specification)
+##  for whether they are defined in a given file.
 ##
 ##=head1 COPYRIGHT
 ##
@@ -16,15 +16,15 @@
 ##
 #-------------------------------------------------------------------------------
 
-DELINT_PATH="${DELINT_PATH:-$(dirname $0)}"
+WARD_PATH="${DELINT_PATH:-$(dirname $0)}"
 
-if ! . "$DELINT_PATH/libdelint"
+if ! . "$WARD_PATH/libdelint"
 then
-  echo "error: could not load $DELINT_PATH/libdelint"
+  echo "error: could not load $WARD_PATH/libdelint"
   exit 1
 fi
 
-function delint_print_usage() {
+function ward_print_usage() {
   cat << EndUsage
 Usage: $(basename $0) [-n] FILE_PATH FILE_TO_CHECK1 [FILE_TO_CHECK2 ...]
 
@@ -36,8 +36,8 @@ used. If passed -n, color output is disabled.
 EndUsage
 }
 
-function delint_usage() {
-  delint_print_usage
+function ward_usage() {
+  ward_print_usage
   exit $ERR_FATAL
 }
 
@@ -49,7 +49,7 @@ then
     LIBCOLOR_NOCOLOR="yes"
     shift
   else
-    delint_usage
+    ward_usage
   fi
 fi
 
@@ -57,11 +57,11 @@ fi
 # the defines file + at least one file to check
 if [[ $# -lt 2 ]]
 then
-  echo "$(delint_print_usage)"
+  echo "$(ward_print_usage)"
   liberror_die $ERR_FATAL
 fi
 
-delint_functions "$@"
+ward_functions "$@"
 
 #-------------------------------------------------------------------------------
 ##
diff --git a/ward/libward b/ward/libward
--- a/ward/libward
+++ b/ward/libward
@@ -3,7 +3,7 @@
 ##
 ##=head1 SYNOPSIS
 ##
-##  Function and variable definitions for the delinters.
+##  Function and variable definitions for the wards.
 ##
 ##=head1 COPYRIGHT
 ##
@@ -19,20 +19,20 @@
 # when grepping, sorting, etc.
 export LC_COLLATE="C"
 
-# ensure that DELINT_PATH has a value
-DELINT_PATH="${DELINT_PATH:-$(dirname $0)}"
+# ensure that WARD_PATH has a value
+WARD_PATH="${WARD_PATH:-$(dirname $0)}"
 
 # load liberror (this is not optional)
-if ! . "$DELINT_PATH/../lib/liberror"
+if ! . "$WARD_PATH/../lib/liberror"
 then
-  echo "error: could not load $DELINT_PATH/../lib/liberror"
+  echo "error: could not load $WARD_PATH/../lib/liberror"
   exit 1
 fi
 
 # load libcolor (there should be an option for this later)
-if ! . "$DELINT_PATH/../lib/libcolor"
+if ! . "$WARD_PATH/../lib/libcolor"
 then
-  echo "error: could not load $DELINT_PATH/../lib/libcolor"
+  echo "error: could not load $WARD_PATH/../lib/libcolor"
   exit 1
 fi
 
@@ -46,7 +46,7 @@ fi
 ## they were found in via libcolor_file.
 ##
 #-------------------------------------------------------------------------------
-function delint_global_variables() {
+function ward_global_variables() {
   local defines=""
   local file=""
 
@@ -89,7 +89,7 @@ function delint_global_variables() {
 ## message there is a matching error code.
 ##
 #-------------------------------------------------------------------------------
-function delint_error_codes() {
+function ward_error_codes() {
   local errorcodes="$1"
   local leader="       "
   local codes=()
@@ -163,7 +163,7 @@ function delint_error_codes() {
 ## found in via libcolor_file.
 ##
 #-------------------------------------------------------------------------------
-function delint_functions() {
+function ward_functions() {
   local path=""
   local file=""
   local prefix=""
@@ -182,12 +182,12 @@ function delint_functions() {
   shift
 
   # make sure we got a good path component
-  if [[ ! -d "$DELINT_PATH/../$path" ]]
+  if [[ ! -d "$WARD_PATH/../$path" ]]
   then
     echo "error: library search path not recognized"
     liberror_die $ERR_FATAL
   else
-    path="$DELINT_PATH/../$path"
+    path="$WARD_PATH/../$path"
   fi
 
   while [[ $# -gt 0 ]]
diff --git a/ward/ward-configvars b/ward/ward-configvars
--- a/ward/ward-configvars
+++ b/ward/ward-configvars
@@ -19,34 +19,34 @@
 #-------------------------------------------------------------------------------
 
 
-DELINT_PATH="${DELINT_PATH:-$(dirname $0)}"
+WARD_PATH="${DELINT_PATH:-$(dirname $0)}"
 
-cauldron="$DELINT_PATH/../cauldron"
+cauldron="$WARD_PATH/../cauldron"
 c_conf="$cauldron/etc/config"
 
-enchantment="$DELINT_PATH/../enchantment"
+enchantment="$WARD_PATH/../enchantment"
 e_conf="$enchantment/etc/config"
 
-if ! . "$DELINT_PATH/libdelint"
+if ! . "$WARD_PATH/libdelint"
 then
-  echo "error: could not load $DELINT_PATH/libdelint"
+  echo "error: could not load $WARD_PATH/libdelint"
   exit 1
 fi
 
 # source the list of cauldron source files to examine
-if ! . "$DELINT_PATH/cauldron_sources"
+if ! . "$WARD_PATH/cauldron_sources"
 then
   echo "error: could not load cauldron_sources"
   exit $ERR_FATAL
 fi
 # source the list of enchantment source files to examine
-if ! . "$DELINT_PATH/enchantment_sources"
+if ! . "$WARD_PATH/enchantment_sources"
 then
   echo "error: could not load enchantment_sources"
   exit $ERR_FATAL
 fi
 
-function delint_print_usage() {
+function ward_print_usage() {
   cat << EndUsage
 Usage: $(basename $0) [-n]
 
@@ -56,8 +56,8 @@ respective errorcodes files. If passed -n, color output is disabled.
 EndUsage
 }
 
-function delint_usage() {
-  delint_print_usage
+function ward_usage() {
+  ward_print_usage
   exit $ERR_FATAL
 }
 
@@ -69,20 +69,20 @@ then
     LIBCOLOR_NOCOLOR="yes"
     shift
   else
-    delint_usage
+    ward_usage
   fi
 fi
 
 # check cauldron files
 libcolor_notice "Checking cauldron config variables"
 echo ""
-delint_global_variables "$c_conf" "${cauldron_srcs[@]}" | \
+ward_global_variables "$c_conf" "${cauldron_srcs[@]}" | \
   grep -v '[^A-Z_]ERR_[A-Z_]*'
 
 # check enchantment files
 libcolor_notice "Checking enchantment config variables"
 echo ""
-delint_global_variables "$e_conf" "${enchantment_srcs[@]}" | \
+ward_global_variables "$e_conf" "${enchantment_srcs[@]}" | \
   grep -v '[^A-Z_]ERR_[A-Z_]*'
 
 #-------------------------------------------------------------------------------
diff --git a/ward/ward-errorcodes b/ward/ward-errorcodes
--- a/ward/ward-errorcodes
+++ b/ward/ward-errorcodes
@@ -17,34 +17,34 @@
 ##
 #-------------------------------------------------------------------------------
 
-DELINT_PATH="${DELINT_PATH:-$(dirname $0)}"
+WARD_PATH="${DELINT_PATH:-$(dirname $0)}"
 
-cauldron="$DELINT_PATH/../cauldron"
+cauldron="$WARD_PATH/../cauldron"
 c_codes="$cauldron/errorcodes"
 
-enchantment="$DELINT_PATH/../enchantment"
+enchantment="$WARD_PATH/../enchantment"
 e_codes="$enchantment/errorcodes"
 
-if ! . "$DELINT_PATH/libdelint"
+if ! . "$WARD_PATH/libdelint"
 then
-  echo "error: could not load $DELINT_PATH/libdelint"
+  echo "error: could not load $WARD_PATH/libdelint"
   exit 1
 fi
 
 # source the list of cauldron source files to examine
-if ! . "$DELINT_PATH/cauldron_sources"
+if ! . "$WARD_PATH/cauldron_sources"
 then
   echo "error: could not load cauldron_sources"
   exit $ERR_FATAL
 fi
 # source the list of enchantment source files to examine
-if ! . "$DELINT_PATH/enchantment_sources"
+if ! . "$WARD_PATH/enchantment_sources"
 then
   echo "error: could not load enchantment_sources"
   exit $ERR_FATAL
 fi
 
-function delint_print_usage() {
+function ward_print_usage() {
   cat << EndUsage
 Usage: $(basename $0) [-n]
 
@@ -54,8 +54,8 @@ respective errorcodes files. If passed -n, color output is disabled.
 EndUsage
 }
 
-function delint_usage() {
-  delint_print_usage
+function ward_usage() {
+  ward_print_usage
   exit $ERR_FATAL
 }
 
@@ -67,30 +67,30 @@ then
     LIBCOLOR_NOCOLOR="yes"
     shift
   else
-    delint_usage
+    ward_usage
   fi
 fi
 
 # check cauldron error codes/messages files for internal consistency
 libcolor_notice "Checking cauldron errorcodes for internal consistency"
 echo ""
-delint_error_codes "$c_codes"
+ward_error_codes "$c_codes"
 
 # check cauldron files
 libcolor_notice "Checking cauldron sources for undefined error codes"
 echo ""
-delint_global_variables "$c_codes" "${cauldron_srcs[@]}" | \
+ward_global_variables "$c_codes" "${cauldron_srcs[@]}" | \
   grep '[^A-Z_]ERR_[A-Z_]*'
 
 # check enchantment error codes/messages files for internal consistency
 libcolor_notice "Checking enchantment errorcodes for internal consistency"
 echo ""
-delint_error_codes "$e_codes"
+ward_error_codes "$e_codes"
 
 # check enchantment files
 libcolor_notice "Checking enchantment sources for undefined error codes"
 echo ""
-delint_global_variables "$e_codes" "${enchantment_srcs[@]}" | \
+ward_global_variables "$e_codes" "${enchantment_srcs[@]}" | \
   grep '[^A-Z_]ERR_[A-Z_]*'
 
 #-------------------------------------------------------------------------------
