ward: missed some of the renamings
Fix libward and ward- references from the renaming.

diff --git a/ward/ward-configvars b/ward/ward-configvars
--- a/ward/ward-configvars
+++ b/ward/ward-configvars
@@ -27,9 +27,9 @@ c_conf="$cauldron/etc/config"
 enchantment="$WARD_PATH/../enchantment"
 e_conf="$enchantment/etc/config"
 
-if ! . "$WARD_PATH/libdelint"
+if ! . "$WARD_PATH/libward"
 then
-  echo "error: could not load $WARD_PATH/libdelint"
+  echo "error: could not load $WARD_PATH/libward"
   exit 1
 fi
 
diff --git a/ward/ward-errorcodes b/ward/ward-errorcodes
--- a/ward/ward-errorcodes
+++ b/ward/ward-errorcodes
@@ -25,9 +25,9 @@ c_codes="$cauldron/errorcodes"
 enchantment="$WARD_PATH/../enchantment"
 e_codes="$enchantment/errorcodes"
 
-if ! . "$WARD_PATH/libdelint"
+if ! . "$WARD_PATH/libward"
 then
-  echo "error: could not load $WARD_PATH/libdelint"
+  echo "error: could not load $WARD_PATH/libward"
   exit 1
 fi
 
diff --git a/ward/ward-functions b/ward/ward-functions
--- a/ward/ward-functions
+++ b/ward/ward-functions
@@ -25,9 +25,9 @@ cauldron="$WARD_PATH/../cauldron"
 
 enchantment="$WARD_PATH/../enchantment"
 
-if ! . "$WARD_PATH/libdelint"
+if ! . "$WARD_PATH/libward"
 then
-  echo "error: could not load $WARD_PATH/libdelint"
+  echo "error: could not load $WARD_PATH/libward"
   exit 1
 fi
 
