cauldron: lib.init: update naming
Update function and variable names both to match recent changes in other parts
of cauldron as well as to have greater internal coherence.

diff --git a/cauldron/lib/lib.init b/cauldron/lib/lib.init
--- a/cauldron/lib/lib.init
+++ b/cauldron/lib/lib.init
@@ -58,7 +58,7 @@ function cauldron_init_img_install() {
 ## Makes the initrd to be used by the ISO on booting.
 ##
 #-------------------------------------------------------------------------------
-function cauldron_init_make_ramdisk() {
+function cauldron_init_ramdisk_make() {
   local initrd="$CAULDRON_TMP/initrd"
   local initmnt="$CAULDRON_TMP/initrd_mount"
 
@@ -90,7 +90,7 @@ function cauldron_init_make_ramdisk() {
 ## Installs the init ramdisk to be used by the ISO on booting.
 ##
 #-------------------------------------------------------------------------------
-function cauldron_init_install_ramdisk() {
+function cauldron_init_ramdisk_install() {
   local ramdisk="$CAULDRON_TMP/initrd.gz"
 
   cauldron_init_img_install "$ramdisk" || return $ERR_INIT_INSTALL_RD
@@ -103,9 +103,9 @@ function cauldron_init_install_ramdisk() {
 ## Makes the initramfs be used by the ISO on booting.
 ##
 #-------------------------------------------------------------------------------
-function cauldron_init_make_ramfs() {
-  local ramdir="$CAULDRON_TMP/initram"
-  local ramfs="$CAULDRON_TMP/initram.cpio.gz"
+function cauldron_init_ramfs_make() {
+  local ramdir="$CAULDRON_TMP/initfs"
+  local ramfs="$CAULDRON_TMP/initfs.gz"
 
   "${CAULDRON_CMD_MKDIR[@]}" "$ramdir" || return $ERR_MK_DIR
 
@@ -126,8 +126,8 @@ function cauldron_init_make_ramfs() {
 ## Installs the init ramfs to be used by the ISO on booting.
 ##
 #-------------------------------------------------------------------------------
-function cauldron_init_install_ramfs() {
-  local ramfs="$CAULDRON_TMP/initram.cpio.gz"
+function cauldron_init_ramfs_install() {
+  local ramfs="$CAULDRON_TMP/initfs.gz"
 
   cauldron_init_img_install "$ramfs"
   liberror_check || return $ERR_INIT_INSTALL_RAMFS
@@ -143,7 +143,7 @@ function cauldron_init_install_ramfs() {
 #-------------------------------------------------------------------------------
 function cauldron_init_fs_dirs() {
   local initfs="$1"
-  local list="$CAULDRON_DATA/$CAULDRON_ARCH/initfs/dirs"
+  local list="$CAULDRON_CONFIG/$CAULDRON_ARCH/initfs/dirs"
 
   if [[ -f "$list" ]]
   then
@@ -164,7 +164,7 @@ function cauldron_init_fs_dirs() {
 #-------------------------------------------------------------------------------
 function cauldron_init_fs_bins() {
   local initfs="$1"
-  local list="$CAULDRON_DATA/$CAULDRON_ARCH/initfs/binaries"
+  local list="$CAULDRON_CONFIG/$CAULDRON_ARCH/initfs/binaries"
 
   if [[ -f "$list" ]]
   then
@@ -185,7 +185,7 @@ function cauldron_init_fs_bins() {
 #-------------------------------------------------------------------------------
 function cauldron_init_fs_libs() {
   local initfs="$1"
-  local list="$CAULDRON_DATA/$CAULDRON_ARCH/initfs/libs"
+  local list="$CAULDRON_CONFIG/$CAULDRON_ARCH/initfs/libs"
 
   if [[ -f "$list" ]]
   then
@@ -206,7 +206,7 @@ function cauldron_init_fs_libs() {
 #-------------------------------------------------------------------------------
 function cauldron_init_fs_mods() {
   local initfs="$1"
-  local list="$CAULDRON_DATA/$CAULDRON_ARCH/initfs/modules"
+  local list="$CAULDRON_CONFIG/$CAULDRON_ARCH/initfs/modules"
 
   if [[ -f "$list" ]]
   then
@@ -230,7 +230,7 @@ function cauldron_init_fs_mods() {
 #-------------------------------------------------------------------------------
 function cauldron_init_fs_init() {
   local initfs="$1"
-  local init_script="$CAULDRON_DATA/$CAULDRON_ARCH/initfs/init"
+  local init_script="$CAULDRON_CONFIG/$CAULDRON_ARCH/initfs/init"
 
   # copy the init script to /init in the init filesystem, because /init is
   # *requried* by init ramfs and an init ramdisk can be configured to use
@@ -248,15 +248,16 @@ function cauldron_init_fs_init() {
 ## @param path_to_initfs (required)
 ## @param path to build directory (optional)
 ##
-## Builds busybox for use in the initramfs using a preconfigured config file for
-## the build. It builds by casting in the build chroot, copies the resulting
-## busybox binary, and then dispels the busybox spell in the chroot to clean up.
+## Builds sysutils (e.g. busybox) for use in the initramfs using a preconfigured
+## config file for the build. It builds by casting in the build chroot, copies
+## the resulting sysutils binary, and then dispels in the chroot to clean up.
 ##
 #-------------------------------------------------------------------------------
-function cauldron_init_fs_busybox() {
+function cauldron_init_fs_sysutils() {
   local initfs="$1"
   local build="${2:-$CAULDRON_BUILD}"
-  local bbconf="$CAULDRON_DATA/$CAULDRON_ARCH/initfs/busybox.config"
+  local util="$CAULDRON_SYSUTILS"
+  local utilconf="$CAULDRON_SYSUTILS_CONF"
 
   if [[ ! -d "$build" ]]
   then
@@ -266,8 +267,8 @@ function cauldron_init_fs_busybox() {
   "${CAULDRON_CMD_MKDIR[@]}" "$build/etc/sorcery/local" || return $ERR_MK_DIR
 
   "${CAULDRON_CMD_CP_FORCE[@]}" \
-    "$bbconf" \
-    "$build/etc/sorcery/local/busybox.config" ||
+    "$utilconf" \
+    "$build/$sorcery/${util}.config" ||
       return $ERR_CP_FILE
 
   cauldron_chroot_init "$build"
@@ -276,10 +277,10 @@ function cauldron_init_fs_busybox() {
   cauldron_chroot_cast "$util"
   liberror_check || return $?
 
-  "${CAULDRON_CMD_CP[@]}" "$build/sbin/busybox" "$initfs/sbin/busybox" ||
+  "${CAULDRON_CMD_CP[@]}" "$build/sbin/$util" "$initfs/sbin/$util" ||
     return $ERR_CP_FILE
 
-  cauldron_chroot_dispel "busybox"
+  cauldron_chroot_dispel "$util"
   liberror_check || return $?
 
   cauldron_chroot_done "$build"
@@ -302,7 +303,7 @@ function cauldron_init_fs_make() {
 
   cauldron_init_fs_dirs "$initfs"
   liberror_check || return $ERR_INIT_MAKE_FS
-  cauldron_init_fs_busybox "$initfs"
+  cauldron_init_fs_sysutils "$initfs"
   liberror_check || return $ERR_INIT_MAKE_FS
   cauldron_init_fs_bins "$initfs"
   liberror_check || return $ERR_INIT_MAKE_FS
