cauldron: more chroot error testing/prevention
For cases where chroot execution is needed, try to ensure that we have
entered a chroot before trying to execute. If there are errors with the
chroot, report the errors rather than trying to run commands inside a
non-existent chroot.

diff --git a/cauldron/lib/libcauldron b/cauldron/lib/libcauldron
--- a/cauldron/lib/libcauldron
+++ b/cauldron/lib/libcauldron
@@ -107,6 +107,8 @@ function cauldron_clean_iso_system() {
 
   [[ -z "$cleanfile" ]] && return $ERR_CLEAN_FILE
 
+  [[ -z "$CAULDRON_CHROOT" ]] && return $ERR_CHROOT_INIT
+
   for i in $(sort -r $cleanfile)
   do
     if [[ -d "$i" ]]
@@ -234,11 +236,17 @@ function cauldron_prepare() {
   # ensure that the build dir exists
   "${CAULDRON_CMD_MKDIR[@]}" "$CAULDRON_BUILD"
 
+  # ensure CAULDRON_BUILD/etc exists
+  "${CAULDRON_CMD_MKDIR[@]}" "$CAULDRON_BUILD/etc"
+
   # copy the host's resolv.conf in order to dl sources from the net
   "${CAULDRON_CMD_CP[@]}" \
     "$CAULDRON_RESOLV" \
     "$CAULDRON_BUILD/etc/resolv.conf" ||
       return $ERR_RESOLV
+
+  # prepare chroots to $CAULDRON_BUILD
+  cauldron_chroot_init || return $?
 
   # install sorcery into the build dir
   if [[ -z cauldron_sorcerous_install ]]
@@ -250,6 +258,9 @@ function cauldron_prepare() {
   # cauldron is a spell
   # there is a spoon
   cauldron_chroot "${CAULDRON_CMD_CAST[@]}" cauldron || return $ERR_CHROOT_CAST
+
+  # clean up the chroot
+  cauldron_chroot_done || return $?
 
   return $ERR_OK
 }
