cauldron and installers/common fixes and formatting
Incorporated various fixes to proactively squash bugs (as well as to flesh out
the implementations) of both cauldron and installers/common. Additionally,
cleaned up the formatting of both files to use 2 spaces for indentations
instead of tabs, and used the "function" keyword to define functions more
explicitly.

diff --git a/src/cauldron b/src/cauldron
--- a/src/cauldron
+++ b/src/cauldron
@@ -24,7 +24,7 @@
 ##
 #---------------------------------------------------------------------
 
-help() {
+function help() {
 
   cat << EOF
 
@@ -36,155 +36,182 @@ EOF
   exit 1
 }
 
-cauldron_enter_chroot() {
-	mount --bind ${HOST}/dev ${CAULDRON_BUILD}/dev
-	mount --bind ${HOST}/dev/pts ${CAULDRON_BUILD}/dev/pts
-	mount --bind ${HOST}/proc ${CAULDRON_BUILD}/proc
+function cauldron_enter_chroot() {
+  mount --bind ${HOST}/dev ${CAULDRON_BUILD}/dev
+  mount --bind ${HOST}/dev/pts ${CAULDRON_BUILD}/dev/pts
+  mount --bind ${HOST}/proc ${CAULDRON_BUILD}/proc
 }
 
-cauldron_exit_chroot() {
-	umount ${CAULDRON_BUILD}/dev
-	umount ${CAULDRON_BUILD}/dev/pts
-	umount ${CAULDRON_BUILD}/proc
+function cauldron_exit_chroot() {
+  umount ${CAULDRON_BUILD}/proc
+  umount ${CAULDRON_BUILD}/dev/pts
+  umount ${CAULDRON_BUILD}/dev
 }
 
-cauldron_create_base_toolchain() {
-	for spell in ${HOST_TOOLCHAIN}
-	do
-		if [[ -f ${HOST_SORCERY_SPOOL}/${spell}-*-${HOST_ARCH}-${HOST_SYSTEM}-linux-gnu.tar.bz2 ]]
-		then
-			cp ${HOST_SORCERY_SPOOL}/${spell}-*-${HOST_ARCH}-${HOST_SYSTEM}-linux-gnu.tar.bz2
-		else
-			cauldron_build_cache_file ${spell}
-		fi
-	done
-	tar xjf ${spell}-*-${HOST_ARCH}.tar.bz2 -C ${CAULDRON_BUILD}/
+function cauldron_create_base_toolchain() {
+  # grab the list of spells needed as the base tool-chain which will be
+  # used to create the cross-compile tool-chain
+  for spell in ${HOST_TOOLCHAIN}
+  do
+    # check to see if there is already a cache file from sorcery
+    # this check could be based on spell-{names,versions} reported by
+    # gaze/sorcery/dispel. Mirroring code in dispel might be the best bet,
+    # since that has to find the version currently installed anyway.
+    if [[ -f ${HOST_SORCERY_SPOOL}/${spell}-*-${HOST_ARCH}.tar.bz2 ]]
+    then
+      # found a cache file, copy it to the BUILD dir
+      cp ${HOST_SORCERY_SPOOL}/${spell}-*-${HOST_ARCH}.tar.bz2 \
+        ${CAULDRON_BUILD}
+    else
+      # couldn't find a cache file, so we'll need to build one
+      cauldron_build_cache_file ${spell}
+    fi
+  done
+
+  # unpack the cache file, effectively installing the spell into the BUILD dir
+  # the unpacking is done against the BUILD dir as the root dir, so
+  # this should not touch the HOST filesystem at all
+  tar xjf ${CAULDRON_BUILD}/${spell}-*-${HOST_ARCH}.tar.bz2 -C \
+    ${CAULDRON_BUILD}/
 }
 
-cauldron_create_target_toolchain() {
-	cauldron_configure_toolchain
-	chroot sorcery rebuild
+function cauldron_create_target_toolchain() {
+  # set sorcery options, etc. for cross-compile
+  cauldron_configure_toolchain
+
+  # do a sorcery rebuild inside the BUILD dir to
+  # generate the cross-compile tool-chain
+  chroot ${CAULDRON_BUILD} "/usr/sbin/sorcery rebuild"
 }
 
-cauldron_build_iso_system() {
+function cauldron_build_iso_system() {
 }
 
-cauldron_iso_init() {
+function cauldron_iso_init() {
 }
 
-cauldron_add_installer() {
+function cauldron_add_installer() {
 }
 
-cauldron_clean_iso_system() {
+function cauldron_clean_iso_system() {
 }
 
-cauldron_mkisofs() {
-	mkisofs -R -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o ${SMGL_ISO} ${CAULDRON_BUILD}
+function cauldron_mkisofs() {
+  mkisofs -R -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot \
+    -boot-load-size 4 -boot-info-table -o ${SMGL_ISO} ${CAULDRON_BUILD}
 }
 
-cauldron_build_iso() {
-	# set up basic tool-chain in order to cross-compile for target later
-	cauldron_create_toolchain
-	
-	# copy the host's resolv.conf in order to dl packages from net
-	cp /etc/resolv.conf ${CAULDRON_BUILD}/
-	
-	# set up chroot for building inside $CAULDRON_BUILD
-	cauldron_enter_chroot
-	
-	# build the cross-compile tool-chain targeted for the target sys
-	cauldron_create_target_toolchain
-	
-	# use the cross-compile tool-chain to cast all spells needed for
-	# the iso system
-	cauldron_build_iso_system
-	
-	# configure the iso init system, initrd/initramfs, etc.
-	cauldron_iso_init
-	
-	# build/create/copy/whatever installer system/data into the iso
-	cauldron_add_installer
-	
-	# remove unnecessary files from iso and free up space
-	cauldron_clean_iso_system
-	
-	# finished with iso building, clean up from chroot setup
-	cauldron_exit_chroot
-	
-	# create the iso fs from the build dir
-	cauldron_mkisofs
+function cauldron_build_iso() {
+  # set up basic tool-chain in order to cross-compile for target later
+  cauldron_create_toolchain
+  
+  # copy the host's resolv.conf in order to dl packages from net
+  cp /etc/resolv.conf ${CAULDRON_BUILD}/
+  
+  # set up chroot for building inside $CAULDRON_BUILD
+  cauldron_enter_chroot
+  
+  # build the cross-compile tool-chain targeted for the target sys
+  cauldron_create_target_toolchain
+  
+  # use the cross-compile tool-chain to cast all spells needed for
+  # the iso system
+  cauldron_build_iso_system
+  
+  # configure the iso init system, initrd/initramfs, etc.
+  cauldron_iso_init
+  
+  # build/create/copy/whatever installer system/data into the iso
+  cauldron_add_installer
+  
+  # remove unnecessary files from iso and free up space
+  cauldron_clean_iso_system
+  
+  # finished with iso building, clean up from chroot setup
+  cauldron_exit_chroot
+  
+  # create the iso fs from the build dir
+  cauldron_mkisofs
 }
 
-cauldron_menu_main() {
-	local CAULDRON_B_HELP="Build directory location"
-	local CAULDRON_OK="Select"
-	local CAULDRON_CANCEL="Exit"
+function cauldron_menu_main() {
+  local CAULDRON_B_HELP="Build directory location"
+  local CAULDRON_OK="Select"
+  local CAULDRON_CANCEL="Exit"
 
-	while
-		CAULDRON_COMMAND=$(eval ${DIALOG} ' --title "Main Menu"		\
-			--item-help						\
-			--ok-label	"${CAULDRON_OK}"			\
-			--cancel-label	"${CAULDRON_CANCEL}"			\
-			--menu							\
-			"Cauldron Version ${CAULDRON_VERSION}"			\
-			0 0 0							\
-			"B" "Build	Menu"	"${CAULDRON_B_HELP}"'		)
-	do
-		case ${CAULDRON_COMMAND} in
-			B) cauldron_menu_build;;
-		esac
-	done
+  while
+    CAULDRON_COMMAND=$(eval ${DIALOG} ' --title "Main Menu"       \
+                            --item-help                           \
+                            --ok-label                            \
+                            "${CAULDRON_OK}"                      \
+                            --cancel-label                        \
+                            "${CAULDRON_CANCEL}"                  \
+                            --menu                                \
+                            "Cauldron Version                     \
+                            ${CAULDRON_VERSION}"                  \
+                            0 0 0                                 \
+                            "B" "Build  Menu"                     \
+                            "${CAULDRON_B_HELP}"'                 )
+  do
+    case ${CAULDRON_COMMAND} in
+      B) cauldron_menu_build;;
+    esac
+  done
 }
 
-cauldron_menu_build() {
-	local CAULDRON_OK="Commit"
-	local CAULDRON_CANCEL="Cancel"
+function cauldron_menu_build() {
+  local CAULDRON_OK="Commit"
+  local CAULDRON_CANCEL="Cancel"
 
-	if CAULDRON_BUILD=$(eval ${DIALOG} ' --ok-label ${CAULDRON_OK}		\
-					--cancel-label ${CAULDRON_CANCEL}	\
-					--input-menu				\
-					"Enter the path to the dir where	\
-					Cauldron should build your ISOs."	\
-					0 0					\
-					${CAULDRON_BUILD}'			)
-	then
-		cauldron_modify_local_config "CAULDRON_BUILD" "${CAULDRON_BUILD}"
-	fi
+  if CAULDRON_BUILD=$(eval ${DIALOG} ' --ok-label                 \
+                          ${CAULDRON_OK}                          \
+                          --cancel-label ${CAULDRON_CANCEL}       \
+                          --input-menu                            \
+                          "Enter the path to the dir where        \
+                          Cauldron should build your ISOs."       \
+                          0 0                                     \
+                          ${CAULDRON_BUILD}'                      )
+  then
+    cauldron_modify_local_config "CAULDRON_BUILD" "${CAULDRON_BUILD}"
+  fi
 }
 
-cauldron_main() {
-	if [[ -z $1 ]]
-	then
-		cauldron_menu_main
-	else
-		case $1 in
-			-h|--help|help) help	;;
-			*) help			;;
-		esac
-	fi
+function cauldron_main() {
+  if [[ -z $1 ]]
+  then
+    cauldron_menu_main
+  else
+    case $1 in
+      -h|--help|help) help  ;;
+      *) help     ;;
+    esac
+  fi
 }
 
 . /etc/cauldron/config
 if [[ $UID == 0 ]]
 then
-	DIALOG='$DIALOG_PROG --backtitle "Cauldron ISO builder and installer management utility" --stdout'
+  DIALOG='$DIALOG_PROG                                            \
+          --backtitle                                             \
+          "Cauldron ISO builder and installer management utility" \
+          --stdout'
 
-	CAULDRON_VERSION=$(cat /etc/cauldron/version)
-	cauldron_main "$@"
-	CAULDRON_STATUS=$?
-	exit ${CAULDRON_STATUS}
+  CAULDRON_VERSION=$(cat /etc/cauldron/version)
+  cauldron_main "$@"
+  CAULDRON_STATUS=$?
+  exit ${CAULDRON_STATUS}
 else
-	if [[ $1 == -h ]] || [[ $1 == --help ]] || [[ $1 == help ]]
-	then
-		cauldron_help
-	elif [[ $1 == -v ]] || [[ $1 == --version ]] || [[ $1 == version ]]
-	then
-		echo $(cat /etc/cauldron/version)
-	else
-		echo "Please enter the root password."
-		CAULDRON_PARAMS=$@
-		su -c "$0 ${CAULDRON_PARAMS}" root
-	fi
+  if [[ $1 == -h ]] || [[ $1 == --help ]] || [[ $1 == help ]]
+  then
+    cauldron_help
+  elif [[ $1 == -v ]] || [[ $1 == --version ]] || [[ $1 == version ]]
+  then
+    echo $(cat /etc/cauldron/version)
+  else
+    echo "Please enter the root password."
+    CAULDRON_PARAMS=$@
+    su -c "$0 ${CAULDRON_PARAMS}" root
+  fi
 fi
 
 #---------------------------------------------------------------------
@@ -207,3 +234,5 @@ fi
 ## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 ##
 #---------------------------------------------------------------------
+
+# vim:ai:tw=80:tabstop=2:softtabstop=2:expandtab
